### ISSUE TITLE
[Help] Textures

### ISSUE THREAD

**Issue by Shovinus** [The-Acronym-Coders/ContentTweaker#137]
Sorry but been trying for a while to add textures to an item, can someone point me to an up to date tutorial?

**Comment by kindlich** [comment]
https://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/WalkThrough/

This one is for a block, though it is almost the same for items.
Simply replace the `blocks` with `items`

**Comment by Shovinus** [comment]
tried that, didn't work :(

**Comment by Shovinus** [comment]
Also adding fluids seem to fail too
```
#loader contenttweaker
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Fluid;
import mods.contenttweaker.Color;

var zsFluid = VanillaFactory.createFluid("zs_fluid", Color.fromHex("FF69B4"));
zsFluid.fillSound = <soundevent:block.anvil.place>;
zsFluid.register();
```
```
[PREINITIALIZATION][CLIENT][ERROR] content.zs:3 > No such member: Fluid
[PREINITIALIZATION][CLIENT][ERROR] content.zs:3 > Not a valid type
[PREINITIALIZATION][CLIENT][ERROR] content.zs:4 > No such member: Color
[PREINITIALIZATION][CLIENT][ERROR] content.zs:4 > Not a valid type
[PREINITIALIZATION][CLIENT][ERROR] content.zs:5 > No such static member in mods.contenttweaker.VanillaFactory: createFluid
[PREINITIALIZATION][CLIENT][ERROR] content.zs:5 > could not find Color
[PREINITIALIZATION][CLIENT][ERROR] Error executing content.zs: 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at stanhebben.zenscript.type.natives.JavaMethod.rematch(JavaMethod.java:168)
	at stanhebben.zenscript.expression.ExpressionCallVirtual.<init>(ExpressionCallVirtual.java:24)
	at stanhebben.zenscript.type.ZenTypeAny.call(ZenTypeAny.java:175)
	at stanhebben.zenscript.expression.Expression.call(Expression.java:79)
```
